version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck