services:
  postgres:
    image: postgres:16-alpine
    container_name: ${POSTGRES_CONTAINER_NAME:-servicedesk-postgres}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 3s
      retries: 20
    volumes:
      - pg_data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: servicedesk-kafka
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

      KAFKA_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://kafka:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
    volumes:
      - kafka_data:/bitnami/kafka

  migrate:
    image: migrate/migrate:v4.17.1
    container_name: servicedesk-migrate
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ../../migrations:/migrations:ro
    # Use service DNS name 'postgres' for in-network access.
    command:
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      - "up"
    restart: "no"

  ticket-service:
    build:
      context: ../..
      dockerfile: cmd/ticket-service/Dockerfile
    container_name: servicedesk-ticket-service
    depends_on:
      migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-dev}
      HTTP_ADDR: ":8080"
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
    ports:
      - "8080:8080"

  outbox-relay:
    build:
      context: ../..
      dockerfile: cmd/outbox-relay/Dockerfile
    container_name: servicedesk-outbox-relay
    depends_on:
      migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: ${KAFKA_TOPIC:-tickets.events}
      KAFKA_CLIENT_ID: "outbox-relay"
      KAFKA_DLQ_TOPIC: ${KAFKA_DLQ_TOPIC:-}
      METRICS_ADDR: ":9090"
      OUTBOX_RELAY_POLL_INTERVAL: ${OUTBOX_RELAY_POLL_INTERVAL:-500ms}
      OUTBOX_RELAY_PROCESSING_TIMEOUT: ${OUTBOX_RELAY_PROCESSING_TIMEOUT:-30s}
      OUTBOX_RELAY_MAX_ATTEMPTS: ${OUTBOX_RELAY_MAX_ATTEMPTS:-10}
    ports:
      - "9090:9090"

  notification-service:
    build:
      context: ../..
      dockerfile: cmd/notification-service/Dockerfile
    container_name: servicedesk-notification-service
    depends_on:
      migrate:
        condition: service_completed_successfully
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC: ${KAFKA_TOPIC:-tickets.events}
      KAFKA_GROUP_ID: ${KAFKA_GROUP_ID:-notification-service}
      KAFKA_START_OFFSET: ${KAFKA_START_OFFSET:-first}
      KAFKA_DLQ_TOPIC: ${KAFKA_DLQ_TOPIC:-}
      NOTIFY_MAX_ATTEMPTS: ${NOTIFY_MAX_ATTEMPTS:-10}
      NOTIFY_FORCE_FAIL: ${NOTIFY_FORCE_FAIL:-0}
      NOTIFY_FORCE_FAIL_EVENT_TYPE: ${NOTIFY_FORCE_FAIL_EVENT_TYPE:-}
      METRICS_ADDR: ":9091"
    ports:
      - "9091:9091"

volumes:
  pg_data:
  kafka_data:
